node {
    stage('build') {
        // some block
        echo 'Build stage'
        catchError(message: 'Error found on build stage') {
            sh label: '', script: './gradlew build'
        }
    }
}