node {
    stage('SCM') {
        echo 'SCM stage'
        git 'https://github.com/ironcero/liferay_integration_test.git'
    }
    stage('build') {
        echo 'Build stage'
        catchError(message: 'Error found on build stage') {
            sh './gradlew build'
        }
    }
    stage('deploy'){
        echo 'Deploy stage'
        sh 'find . -type f -path \*/modules/\*/build/libs/*.jar -exec cp -v {} /var/liferay_deploy/.'
    }
}